name: lorenzapanero
favicon: null
layout_spectrum: 0.60195
typography_spectrum: 0.24945322307758033
title: Lumnographs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e2f6'
    - '#250e0f'
    - '#0065ab'
    - '#dd44cd'
    - '#da6300'
  brandStrength: 0.33559703384526074
  lightness: 0.24254704941995442
  saturation: 0.9987161313183606
  rhythmicContrast: 0.3675961752887815
purpose: []
